### ISSUE TITLE
picovoice command failed

### ISSUE THREAD

**Issue by jcmag** [Nikro/MMM-WhisperGPT#6]
Hi,

I've installed MagicMirror, and MMM-WhisperGPT module, but when I run npm run start:dev, I get this error:

> [2024-05-13 13:01:19.769] [ERROR] (node:92349) UnhandledPromiseRejectionWarning: Error: Command failed: "/home/pi/MagicMirror/modules/MMM-WhisperGPT/node_modules/@picovoice/pvrecorder-node/scripts/platform.sh"
    at checkExecSyncError (node:child_process:905:11)
    at execSync (node:child_process:977:15)
    at node:electron/js2c/node_init:2:13035
    at PvRecorder._getLibraryPath (/home/pi/MagicMirror/modules/MMM-WhisperGPT/node_modules/@picovoice/pvrecorder-node/dist/pv_recorder.js:149:51)
    at <static_initializer> (/home/pi/MagicMirror/modules/MMM-WhisperGPT/node_modules/@picovoice/pvrecorder-node/dist/pv_recorder.js:22:45)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-WhisperGPT/node_modules/@picovoice/pvrecorder-node/dist/pv_recorder.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-WhisperGPT/node_modules/@picovoice/pvrecorder-node/dist/index.js:14:23)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
(Use `electron --trace-warnings ...` to show where the warning was created) 
[2024-05-13 13:01:19.775] [ERROR] (node:92349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by F-Fichter** [comment]
hello, i have some problem with this too, where are you find the logs ?
